pain/urls.py
from django.urls import path
from . import views


app_name = 'pain'

urlpatterns = [
    # ex: /
    path('', views.index, name='index'),
]

painmobile/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('headache/', include('headache.urls')),
    path('stomachpain/', include('stomachpain.urls')),
    path('', include('pain.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stomachpain/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views


app_name = 'stomachpain'

urlpatterns = [
    # ex: /stomachpain/
    path('', views.index, name='index'),
    # ex: /stomachpain/edit/id/
    path('edit/<int:question_id>/', views.edit, name='edit'),
    # ex: /stomachpain/delete/id/
    path('delete/<int:question_id>/', views.delete, name='delete'),
    # ex: /stomachpain/add/
    path('add/', views.add, name='add'),
    # ex: /stomachpain/submit/
    path('submit/', views.submit, name='submit'),

    #JSON list of questions
    path('json/list/', views.questions_list_json, name='questions_list_json'),
    #JSON change questions order
    path('json/order/', views.questions_order_update_json, name='questions_order_update_json'),

    # ex: /stomachpain/drug/add
    path('drug/add/', views.drug_add, name='drug_add'),
    # ex: /stomachpain/drug/delete
    path('drug/delete/<int:drug_id>/', views.drug_delete, name='drug_delete'),
    # ex: /stomachpain/drug/add
    path('drug/edit/<int:drug_id>/', views.drug_edit, name='drug_edit'),
    # ex: /stomachpain/drug/submit
    path('drug/submit/', views.drug_submit, name='drug_submit'),

]

stomachpain/models.py
from django.db import models
from django.conf import settings
# Create your models here.

class Drug(models.Model):
    drug_name = models.CharField('Название препарата', max_length=200, default="")
    image_file = models.ImageField(null=True, blank=True)
    contraindications_text = models.CharField('Есть ли у вас (противопоказания)', max_length=2000, default="")
    precautions_text = models.CharField('Есть ли у вас (предостережения)', max_length=2000, default="")
    drug_guide_url = models.URLField('Ссылка на препарат')
    def __str__(self):
        return self.drug_name

class Question(models.Model):
    question_order_id = models.IntegerField('Порядковый номер', default=0)
    question_text = models.CharField('Текст вопроса', max_length=100, default="")
    diagnosis_text = models.CharField('Диагноз', max_length=2000, default="")
    recommendations_text = models.CharField('Рекомендации', max_length=2000, default="")
    interrupt_boolean = models.BooleanField(default=False)
    drugs = models.ManyToManyField(Drug)

    def __str__(self):
        return self.question_text

stomachpain/forms.py
from django import forms
from .models import Drug
from .validators import validate_file_extension

class QuestionForm(forms.Form):
	question_id = forms.CharField(label='',widget=forms.HiddenInput())
	question_order_id = forms.CharField(widget=forms.HiddenInput())
	question_text = forms.CharField(label='Вопрос:', required=False)
	diagnosis_text = forms.CharField(label='Диагноз:', widget=forms.Textarea, required=False)
	recommendations_text = forms.CharField(label='Рекомендации:', widget=forms.Textarea, required=False)
	interrupt_boolean = forms.BooleanField(label='Прервать опросник в связи с состоянием пациента', required=False)
	drugs = forms.ModelMultipleChoiceField(label='Рекомендуемые препараты', required=False, widget=forms.CheckboxSelectMultiple, queryset=Drug.objects.all())

class DrugForm(forms.Form):
	drug_id = forms.CharField(label='',widget=forms.HiddenInput())
	drug_name = forms.CharField(label='Название препарата:')
	image_file = forms.ImageField(label='Изображение:', required=False, validators=[validate_file_extension], widget=forms.ClearableFileInput)
	contraindications_text = forms.CharField(label='Противопоказания:', widget=forms.Textarea, required=False)
	precautions_text = forms.CharField(label='Предосторожности:', widget=forms.Textarea, required=False)
	drug_guide_url = forms.URLField(label='Ссылка на препарат:', required=False)

stomachpain/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.db.models import Max
from django import forms


# Create your views here.

from .models import Question, Drug
from .forms import QuestionForm, DrugForm

# Imports for REST API

from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.renderers import JSONRenderer
from rest_framework.parsers import JSONParser
from .serializers import QuestionSerializer

from .dictionary import dictionary

# file upload functions

from .file_management import handle_uploaded_file

def index(request):
    latest_question_list = Question.objects.order_by('question_order_id')
    latest_drug_list = Drug.objects.order_by('id')
    context = {
    	'latest_question_list': latest_question_list,
    	'latest_drug_list': latest_drug_list,
    	'dictionary': dictionary,
    }
    return render(request, 'stomachpain/index.html', context)

def edit(request, question_id):
	# если question_id не указан, то будет вызвана ошибка 404
	question_to_edit = get_object_or_404(Question, pk=question_id)
	# Заполняем форму данными из БД
	form = QuestionForm( initial= {
		'question_id': question_to_edit.id,
		'question_order_id': question_to_edit.question_order_id,
		'question_text': question_to_edit.question_text,
		'diagnosis_text': question_to_edit.diagnosis_text,
		'recommendations_text': question_to_edit.recommendations_text,
		'interrupt_boolean': question_to_edit.interrupt_boolean,
		'drugs': question_to_edit.drugs.all(),
		})
	message = 'Редактировать вопрос'
	return render(request, 'stomachpain/question.html', {'form': form, 'message': message, 'dictionary': dictionary,})

def delete(request, question_id):
	if question_id>0:
		question_to_delete = get_object_or_404(Question, pk=question_id)
		question_to_delete.delete()
		# После удаления записи сортируем вопросы по заданному порядку
		# и выводим index
		return redirect('/stomachpain/')
	else: 
		raise forms.ValidationError("Не указан или неверный номер для удаления")

def add(request):
	# выводим пустую форму
	# --------------------
	# получаем максимальный порядковый номер в списке вопросов
	# и делаем инкремент
	tmp = Question.objects.all().aggregate(Max('question_order_id'))['question_order_id__max']
	if tmp is None:
		max_question_order_id = 0
	else:
		max_question_order_id = int(tmp)
	form = QuestionForm( initial= {
		'question_order_id': max_question_order_id+1,
		'question_id': -1,
		})
	message = 'Добавить вопрос'
	return render(request, 'stomachpain/question.html', {'form': form, 'message': message, 'dictionary': dictionary,})

def submit(request):
	# Возможны два случая submit:
 	# - В submit передаются данные нового вопроса [add] => question_id = -1
	# - В submit передаются данные редактируемого вопроса [edit], question_id = текущему id autoincrement вопроса
	#
	# Проверяем чтобы данные были переданы через POST
	if request.method == 'POST':
		form = QuestionForm(request.POST)
		if form.is_valid():
			# Проверяем новая ли это запись или редактируемая
			if form.cleaned_data['question_id'] == "-1":
				# case: новая
				# создаем новый объект Question
				question_to_add = Question()
				# заполняем его
				tmp = Question.objects.all().aggregate(Max('question_order_id'))['question_order_id__max']
				if tmp is None:
					max_question_order_id = 1
				else:
					max_question_order_id = int(tmp)+1
				question_to_add.question_order_id = max_question_order_id
				question_to_add.question_text = form.cleaned_data['question_text']
				question_to_add.diagnosis_text = form.cleaned_data['diagnosis_text']
				question_to_add.recommendations_text = form.cleaned_data['recommendations_text']
				question_to_add.interrupt_boolean = form.cleaned_data['interrupt_boolean']
				question_to_add.save()
				drugs_list = form.cleaned_data['drugs']
				drugs_list_ids = [drugs_list.id for drugs_list in drugs_list]
				drugs = Drug.objects.filter(id__in=drugs_list_ids)
				for drug in drugs:
					question_to_add.drugs.add(drug)
				question_to_add.save()
				# выводим редактор с заполненными полями
				#return render(request, 'stomachpain/question.html', {'form': form, 'dictionary': dictionary,})
				return redirect('/stomachpain/')
			else:
				#case: редактируем
				# вытаскиваем из БД объект с нужным id
				question_to_edit = get_object_or_404(Question, pk=form.cleaned_data['question_id'])
				# переписываем поля
				question_to_edit.question_order_id = form.cleaned_data['question_order_id']
				question_to_edit.question_text = form.cleaned_data['question_text']
				question_to_edit.diagnosis_text = form.cleaned_data['diagnosis_text']
				question_to_edit.recommendations_text = form.cleaned_data['recommendations_text']
				question_to_edit.interrupt_boolean = form.cleaned_data['interrupt_boolean']
				# выгружаем список drugs
				drugs_list = form.cleaned_data['drugs']
				drugs_list_ids = [drugs_list.id for drugs_list in drugs_list]
				drugs = Drug.objects.filter(id__in=drugs_list_ids)
				question_to_edit.drugs.clear()
				for drug in drugs:
					question_to_edit.drugs.add(drug)
				question_to_edit.save()
				# выводим редактор с заполненными полями
				# return render(request, 'stomachpain/question.html', {'form': form, 'dictionary': dictionary,})
				return redirect('/stomachpain/')
		else:
			raise forms.ValidationError("Неверные данные в форме")
	else:
		raise forms.ValidationError("Неверный метод передачи данных (не POST) или данные отсутствуют")

@csrf_exempt
def questions_list_json(request):
    ###############
    # List all questions
    ###############
	questions = Question.objects.all().order_by('question_order_id')
	serializer = QuestionSerializer(questions, many = True)
	return JsonResponse(serializer.data, safe = False)

@csrf_exempt
def questions_order_update_json(request):
	if request.method == 'POST':
		data = JSONParser().parse(request)
		print(data)
		for record in data:
			question_id = int(record['question_id'])
			question_to_order = get_object_or_404(Question, pk=question_id)
			question_to_order.question_order_id = int(record['order_id'])
			question_to_order.save()
		return HttpResponse( content_type = "application/json",status = 200)
	else:
		return JsonResponse(serializer.errors, status = 400)

def drug_add(request):
	# выводим пустую форму для добавления препарата
	form = DrugForm( initial= {
		'drug_id': -1,
		})
	message = 'Добавить препарат'
	return render(request, 'stomachpain/drug.html', {'form': form, 'message': message, 'dictionary': dictionary,})

def drug_edit(request, drug_id):
	# если drug_id не указан, то будет вызвана ошибка 404
	drug_to_edit = get_object_or_404(Drug, pk=drug_id)
	# Заполняем форму данными из БД
	form = DrugForm( initial= {
		'drug_id': drug_to_edit.id,
		'image_file': drug_to_edit.image_file,
		'drug_name': drug_to_edit.drug_name,
		'contraindications_text': drug_to_edit.contraindications_text,
		'precautions_text': drug_to_edit.precautions_text,
		'drug_guide_url': drug_to_edit.drug_guide_url,
		})
	message = 'Редактировать препарат'
	image_url = drug_to_edit.image_file.url
	return render(request, 'stomachpain/drug.html', {'form': form, 'message': message, 'drug_id': drug_id, 'image_url': image_url, 'dictionary': dictionary, })


def drug_delete(request, drug_id):
		drug_to_delete = get_object_or_404(Drug, pk=drug_id)
		drug_to_delete.delete()
		return redirect('/stomachpain/')

def drug_submit(request):
	# Возможны два случая submit:
 	# - В submit передаются данные нового препарата [add] => drug_id = -1
	# - В submit передаются данные редактируемого препарата [edit], drug_id = текущему id = primary_key
	#
	# Проверяем чтобы данные были переданы через POST
	if request.method == 'POST':
		form = DrugForm(request.POST, request.FILES)
		if form.is_valid():
			# Проверяем новая ли это запись или редактируемая
			if form.cleaned_data['drug_id'] == "-1":
				# case: новая
				# создаем новый объект Drug
				drug_to_add = Drug()
				# заполняем Drug
				drug_to_add.drug_name = form.cleaned_data['drug_name']
				drug_to_add.contraindications_text = form.cleaned_data['contraindications_text']
				drug_to_add.precautions_text = form.cleaned_data['precautions_text']
				drug_to_add.drug_guide_url = form.cleaned_data['drug_guide_url']
				# сохраняем изображение
				drug_to_add.image_file = request.FILES['image_file']
				drug_to_add.save()
				return redirect('/stomachpain/')
			else:
				#case: редактируем
				# вытаскиваем из БД объект с нужным id
				drug_to_edit = get_object_or_404(Drug, pk=form.cleaned_data['drug_id'])
				# переписываем поля
				drug_to_edit.drug_name = form.cleaned_data['drug_name']
				drug_to_edit.contraindications_text = form.cleaned_data['contraindications_text']
				drug_to_edit.precautions_text = form.cleaned_data['precautions_text']
				drug_to_edit.drug_guide_url = form.cleaned_data['drug_guide_url']

				if 'image_file-clear' in request.POST:
					# если стоит галочка "удалить картинку"
					drug_to_edit.image_file = None
				else:
					if 'image_file' in request.FILES:
						# если файл приложили
						drug_to_edit.image_file = request.FILES['image_file']
						# если файл не приложили
						# НИЧЕГО НЕ ДЕЛАЕМ
				drug_to_edit.save()
				return redirect('/stomachpain/')
				
		else:
			raise forms.ValidationError(form.errors)
	else:
		raise forms.ValidationError("Неверный метод передачи данных (не POST) или данные отсутствуют")

stomachpain/templates/stomachpain/drug.html
<!DOCTYPE HTML>
<html>
<head>
<!-- Embedding Font Awesome for icons -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
</head>
<body>
<div class="app_name">{{ dictionary.app_name }}</div>
{% if form %}
	<div class="editor_wrapper">
		<a href="{% url 'stomachpain:index' %}">&lt; назад к списку вопросов</a>
		{% if message %}
			<h1> {{ message }}</h1>
		{% endif %}
		{% if image_url %}
		<div class="drug_preview" style="background-image: url('{{ image_url }}')"></div>
		{% endif %}
		<form action="{% url 'stomachpain:drug_submit' %}" method="post" enctype="multipart/form-data">
			{% csrf_token %}
    		{{ form }}
    		<br><br>
			<input type="submit" value="Сохранить"> 
			{% if drug_id %}
				<a href="{% url 'stomachpain:drug_delete' drug_id %}" class="drug-delete"><i class="fas fa-trash-alt"></i> Удалить</a>
			{% endif %}
		</form>


	</div>
{% else %}
    <p>Такого препарата нет</p>
{% endif %}

<style>
	body {
		font-family: sans-serif;
		font-size: 13px;
		background-color: #ddd;
	}
	.app_name {
		font-size: 20px;
		font-weight: bold;
		text-align: center;
		display: block;
		height: auto;
		padding: 10px;
		background-color: #a5d6ea;
		border-radius: 50px;
	}
	label {
		display: block;
		margin-top: 20px;
		font-weight: bold;
		font-size: 14px;
		clear: both;
	}

	label[for=image_file-clear_id] {
		display: inline-block;
	}

	.drug_preview {
		width: 200px;
		height: 200px;
		background-position: center center;
		background-size: cover;
		border: 1px solid lightgray;
	}

	#id_drug_name {
		font-size: 26px;
	}

	#id_drug_guide_url {
		width: 300px;
	}

	textarea {
		font-size: 14px;
	}

	.editor_wrapper {
		background-color: white;
		border-radius: 5px;
		display: block;
		padding: 20px;
		margin: 20px;
		margin-bottom: 30px;
    	box-shadow: 5px 5px 10px #bbb;
	}

	.editor_wrapper input[type=submit] {
		padding: 8px;
		background-color: #1887b0;
		border-radius: 3px;
		display: inline-block;
		margin: 0 5px;
		text-decoration: none;
		color: white;
	    -webkit-transition: background-color 500ms ease-out;
	    -moz-transition: background-color 500ms ease-out;
    	-o-transition: background-color 500ms ease-out;
    	transition: background-color 500ms ease-out;
    	border: 0;
    	font-size: 13px;
	} 

	.editor_wrapper input[type=submit]:hover, input[type=submit]:active  {
		background-color: #599611;
		cursor: pointer;
	} 

	#id_question_id {
		border: none;
		width: 30px;
	}

	#id_question_text {
		font-size: 20px;
		width: 100%;
		height: 30px;
	}

	#id_diagnosis_text {
		width: 100%;
		height: 100px;
		border-top: 3px solid #2569be;
	}

	#id_recommendations_text {
		width: 100%;
		height: 100px;
		border-top: 3px solid #82be25;
	}

	#id_contraindications_text {
		width: 100%;
		height: 100px;
		border-top: 3px solid red;
	}

	#id_precautions_text {
		width: 100%;
		height: 100px;
		border-top: 3px solid orange;
	}

	.drug-delete {
		padding: 8px;
		background-color: #1887b0;
		border-radius: 3px;
		display: inline-block;
		margin: 0 5px;
		text-decoration: none;
		color: white;
	    -webkit-transition: background-color 500ms ease-out;
	    -moz-transition: background-color 500ms ease-out;
    	-o-transition: background-color 500ms ease-out;
    	transition: background-color 500ms ease-out;
	}

	.drug-delete:hover {
		background-color: #ac1b17;
	}

</style>


</body>
</html>

stomachpain/templates/stomachpain/question.html
<!DOCTYPE HTML>
<html>
<head>
<!-- Embedding Font Awesome for icons -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
</head>
<body>
<div class="app_name">{{ dictionary.app_name }}</div>
{% if form %}
	<div class="editor_wrapper">
		<a href="{% url 'stomachpain:index' %}">&lt; назад к списку вопросов</a>
		{% if message %}
			<h1> {{ message }}</h1>
		{% endif %}
		<form action="{% url 'stomachpain:submit' %}" method="post">
			{% csrf_token %}
    		{{ form }}
			<br><br><input type="submit" value="Сохранить и вернуться к списку">
		</form>
	</div>
{% else %}
    <p>Такого вопроса нет</p>
{% endif %}

<style>
	body {
		font-family: sans-serif;
		font-size: 13px;
		background-color: #ddd;
	}
	.app_name {
		font-size: 20px;
		font-weight: bold;
		text-align: center;
		display: block;
		height: auto;
		padding: 10px;
		background-color: #a5d6ea;
		border-radius: 50px;
	}
	label {
		display: block;
		margin-top: 20px;
		font-weight: bold;
		font-size: 14px;
	}

	ul {
		margin-top: 5px;
	}

	li {
		list-style: none;
	}

	li > label {
		display: inherit;
		margin-top: 2px;
	}

	textarea {
		font-size: 14px;
	}

	.editor_wrapper {
		background-color: white;
		border-radius: 5px;
		display: block;
		padding: 20px;
		margin: 20px;
		margin-bottom: 30px;
    	box-shadow: 5px 5px 10px #bbb;
	}

	.editor_wrapper input[type=submit] {
		padding: 8px;
		background-color: #1887b0;
		border-radius: 3px;
		display: inline-block;
		margin: 0 5px;
		text-decoration: none;
		color: white;
		font-size: 13px;
	    -webkit-transition: background-color 500ms ease-out;
	    -moz-transition: background-color 500ms ease-out;
    	-o-transition: background-color 500ms ease-out;
    	transition: background-color 500ms ease-out;
	} 

	.editor_wrapper input[type=submit]:hover, input[type=submit]:active  {
		background-color: #599611;
		cursor: pointer;
	} 

	#id_question_id {
		border: none;
		width: 30px;
	}

	#id_question_text {
		font-size: 20px;
		width: 100%;
		height: 30px;
	}

	#id_diagnosis_text {
		width: 100%;
		height: 100px;
		border-top: 3px solid #2569be;
	}

	#id_recommendations_text {
		width: 100%;
		height: 100px;
		border-top: 3px solid #82be25;
	}

	#id_contraindications_text {
		width: 100%;
		height: 100px;
		border-top: 3px solid red;
	}

	#id_precautions_text {
		width: 100%;
		height: 100px;
		border-top: 3px solid orange;
	}

</style>


</body>
</html>